############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

# Install the private All Access Blox from the `hugo-blox/blox/` folder
mounts:
  - source: hugo-blox/blox
    target: layouts/partials/blox/
    includeFiles: '**.html'
  - source: layouts
    target: layouts
